### ISSUE TITLE
Buffalo v0.10.3

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/gobuffalo#108]
This issue keeps track of **changes** in the Buffalo 0.10.3 version, to ensure they are documented before the release.

Buffalo:
- [x] Support Unix domain sockets to bind Buffalo
- [x] StrictSlash should be customizable
- [x] added easy support for file uploads
- [x] added a flag to generate apps with bootstrap 4
- [ ] .env support

**Comment by paganotoni** [comment]
We should also document .env support

**Comment by stanislas-m** [comment]
@paganotoni sure, go ahead! :+1:

**Comment by paganotoni** [comment]
@stanislas-m which section do you think we should add this `.env` documentation ?

**Comment by stanislas-m** [comment]
@paganotoni Hum, in a new section in the Advanced Usage?

**Comment by paganotoni** [comment]
Yup, sounds good! @stanislas-m LMK if you need further changes, i just created a PR in #124

**Comment by stanislas-m** [comment]
@paganotoni Since the v0.10.3 is already released, I'm closing this issue. We'll continue on #124.
