### ISSUE TITLE
Buffalo v0.10.2

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/gobuffalo#87]
This issue keeps track of **changes** in the Buffalo 0.10.2 version, to ensure they are documented before the release.

Buffalo:
- [x] Simplify i18n
- [x] Proposal: move github.com/gobuffalo/x/mail into Buffalo "Core" fixes #752
- [x] no longer need extensions for templates in actions or partials for HTML, JS, and Markdown 
- [x] Provide a way to load custom inflection rules
- [x] Localized views
- [x] Running a single test

Plush:
- [x] Variadic functions support
